import type { Metadata } from "next";
import type { ReactNode } from "react";
import Navbar from "../components/navbar";
import Logo from "../components/logo";
import { Reveal } from "../components/anim";
import { PRIVACY_EMAIL, STUDIO_NAME } from "../lib/site";

export const metadata: Metadata = {
  title: "Privacy Policy — Aks",
  description:
    "The Privacy Policy for Aks: what information may be collected, how it is used, and the choices available to you.",
  alternates: { canonical: "/privacy" },
};

const container = "mx-auto w-full max-w-[1200px] px-5 md:px-8";

function Mail() {
  return (
    <a
      href={`mailto:${PRIVACY_EMAIL}`}
      className="font-medium break-all text-[#171717] underline underline-offset-4"
    >
      {PRIVACY_EMAIL}
    </a>
  );
}

function P({ children }: { children: ReactNode }) {
  return <p className="mt-3 text-[15.5px] leading-[1.7] text-[#444443]">{children}</p>;
}

function List({ items }: { items: string[] }) {
  return (
    <ul className="mt-3 list-disc space-y-1.5 pl-5 text-[15.5px] leading-[1.7] text-[#444443]">
      {items.map((item) => (
        <li key={item}>{item}</li>
      ))}
    </ul>
  );
}

function Section({ n, title, children }: { n: string; title: string; children: ReactNode }) {
  return (
    <Reveal>
      <section className="border-t border-[#E8E8E5] py-8">
        <h2 className="text-[19px] font-medium text-[#171717]">
          <span className="mr-2 font-mono text-[13px] text-[#9a9a96]">{n}</span>
          {title}
        </h2>
        {children}
      </section>
    </Reveal>
  );
}

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#FAFAF8] text-[#171717]">
      <Navbar />
      <main className={`${container} max-w-[720px] py-14 md:py-20`}>
        <Reveal>
          <h1 className="text-[34px] leading-[1.1] font-medium tracking-[-0.025em] md:text-[44px]">
            Privacy Policy for Aks
          </h1>
          <p className="mt-4 font-mono text-[13px] leading-relaxed text-[#6B6B6B]">
            Effective Date: September 22, 2026
            <br />
            Last Updated: September 22, 2026
          </p>
          <div className="mt-6 text-[16px] leading-[1.7] text-[#444443]">
            <p>
              Aks is a personal companion developed by Harsh Kumar Singh at Miyal.
            </p>
            <p className="mt-3">
              This Privacy Policy explains what information Aks may collect, how we use it,
              when it may be shared, and the choices available to you.
            </p>
            <p className="mt-3">
              We have written this policy in plain language because privacy information
              should be understandable.
            </p>
            <p className="mt-3">
              By using Aks, you agree to the practices described in this Privacy Policy.
            </p>
          </div>
        </Reveal>

        <div className="mt-6">
          <Section n="1" title="Who Is Responsible for Your Data?">
            <P>Aks is developed by:</P>
            <P>
              Harsh Kumar Singh
              <br />
              Miyal
            </P>
            <P>
              Privacy contact: <Mail />
            </P>
          </Section>

          <Section n="2" title="Information You Provide to Aks">
            <P>Depending on how you use Aks, we may process:</P>
            <P>
              Your name, email address, account ID, authentication information, and
              profile information.
            </P>
            <P>
              Conversations, including messages you send, responses generated by Aks,
              conversation history, topics discussed, and information provided through
              voice input.
            </P>
            <P>
              Please do not provide information that you do not want Aks or the services
              it uses to process.
            </P>
          </Section>

          <Section n="3" title="Voice and Microphone">
            <P>
              Aks may request access to your device microphone when you use voice features.
            </P>
            <P>
              When voice input is active, your speech may be processed to convert it into
              text and provide the requested feature. Depending on the voice feature and
              service being used, audio or speech data may be transmitted to a
              speech-recognition or AI service for processing.
            </P>
            <P>Aks does not access your microphone when a voice feature is not active.</P>
            <P>You can revoke microphone permission through your device settings.</P>
          </Section>

          <Section n="4" title="Connected Services">
            <P>Aks can connect with services that you choose to use with the app.</P>
            <P>
              Depending on the integrations you enable and the permissions you grant,
              these services may include:
            </P>
            <List
              items={[
                "Google Calendar",
                "Google Tasks",
                "Gmail",
                "Todoist",
                "GitHub",
                "Slack",
                "Notion",
                "Your device calendar",
                "Your device reminders or tasks",
                "Other services supported by Aks in the future",
              ]}
            />
            <P>
              The information available to Aks depends on the service and permissions you
              grant. This may include calendar events, tasks, reminders, Gmail metadata,
              or information made available through GitHub, Slack, Notion, or Todoist.
            </P>
            <P>
              Connected-service information is used to provide features, answer requests,
              and provide relevant context within Aks.
            </P>
            <P>
              You choose which services to connect. Where supported, you can disconnect a
              service at any time.
            </P>
          </Section>

          <Section n="5" title="Location Information">
            <P>
              If you enable a location-based feature and grant the required permission,
              Aks may access your device location.
            </P>
            <P>
              Location information may be used to provide features that depend on your
              location or to provide relevant context.
            </P>
            <P>You can disable location permission through your device settings.</P>
          </Section>

          <Section n="6" title="Calendar, Reminders, and Device Information">
            <P>
              Where supported and where you grant permission, Aks may access information
              from your device calendar, reminders, tasks, or other supported device
              features.
            </P>
            <P>
              This information is used to provide the features you request and to give Aks
              relevant context when appropriate.
            </P>
            <P>You can manage these permissions through your device settings.</P>
          </Section>

          <Section n="7" title="Profile Photos">
            <P>
              If Aks provides a profile-photo feature, you may choose a photo from your
              device to use as your profile image.
            </P>
            <P>
              Aks only receives the photo you select for this purpose. It does not need
              access to your entire photo library simply to set a profile photo.
            </P>
          </Section>

          <Section n="8" title="Screen Time and Other Device Information">
            <P>
              Where supported, Aks may access screen-time or similar device information
              only when you explicitly enable the related feature and grant the required
              permission.
            </P>
            <P>
              This information is used to provide the feature for which it was requested.
            </P>
            <P>Aks does not collect this information simply because you install the app.</P>
          </Section>

          <Section n="9" title="Information Collected Automatically">
            <P>
              When you use Aks, certain technical information may be processed
              automatically. This may include:
            </P>
            <List
              items={[
                "Device type and operating system",
                "Operating-system version",
                "Aks app version",
                "Diagnostic information",
                "Error and crash information",
                "Network or connection information",
                "Authentication and session information",
                "Security-related information",
              ]}
            />
            <P>
              This information may be used to operate Aks, maintain reliability,
              troubleshoot problems, protect accounts, and prevent misuse.
            </P>
            <P>Aks does not use this information to create advertising profiles.</P>
          </Section>

          <Section n="10" title="How We Use Your Information">
            <P>We may use information to:</P>
            <List
              items={[
                "Provide and operate Aks",
                "Respond to your requests and conversations",
                "Provide voice and speech features",
                "Use connected services that you have enabled",
                "Provide relevant context within the app",
                "Maintain and improve reliability",
                "Detect, investigate, and prevent security problems or misuse",
                "Manage authentication and accounts",
                "Process subscriptions and payments",
                "Comply with applicable legal obligations",
              ]}
            />
          </Section>

          <Section n="11" title="AI and Speech Services">
            <P>
              Some Aks features may rely on third-party artificial intelligence,
              speech-recognition, or related technology providers.
            </P>
            <P>
              When you use a feature that requires such a provider, information
              necessary to provide that feature may be sent to the relevant provider.
              Depending on the feature, this may include conversation content, voice or
              speech data, and relevant context from services you have connected.
            </P>
            <P>
              These providers process information to provide the requested service to Aks.
            </P>
            <P>
              We do not sell your conversations or personal information to AI providers
              or advertisers.
            </P>
            <P>
              The specific providers used by Aks may change as the product develops. When
              this happens, we will continue to apply appropriate privacy and security
              requirements.
            </P>
          </Section>

          <Section n="12" title="Third-Party Services">
            <P>
              Aks may use third-party services to operate its features and
              infrastructure, including:
            </P>
            <List
              items={[
                "Supabase",
                "RevenueCat",
                "Google services",
                "Todoist",
                "GitHub",
                "Slack",
                "Notion",
                "Speech and AI service providers",
                "Apple platform services",
                "Google platform services",
              ]}
            />
            <P>
              These services may process information on our behalf or as necessary to
              provide an integration or platform feature you requested.
            </P>
            <P>
              Each third-party service may also have its own privacy policy and terms.
            </P>
          </Section>

          <Section n="13" title="We Do Not Sell Your Personal Information">
            <P>We do not sell your personal information to advertisers or data brokers.</P>
            <P>
              We do not create advertising profiles from your conversations or
              connected-service information for the purpose of selling advertisements.
            </P>
          </Section>

          <Section n="14" title="Security">
            <P>
              We use reasonable technical and organizational measures intended to protect
              your information against unauthorized access, loss, misuse, alteration, or
              disclosure.
            </P>
            <P>
              These measures may include access controls, authentication protections,
              secure connections, and appropriate security practices for the services
              used by Aks.
            </P>
            <P>
              No internet service can guarantee absolute security. If a security incident
              materially affects your information, we will take the steps required by
              applicable law.
            </P>
          </Section>

          <Section n="15" title="How Long We Keep Information">
            <P>
              We retain information for as long as reasonably necessary to provide Aks
              and its features, maintain your account, meet legal obligations, resolve
              disputes, enforce agreements, and protect the service.
            </P>
            <P>Different types of information may be kept for different periods.</P>
            <P>For example:</P>
            <List
              items={[
                "Account information may be retained while your account remains active.",
                "Conversation information may be retained so that you can access conversation history and related features.",
                "Connected-service information may be retained as necessary to provide the relevant feature.",
                "Subscription and transaction information may be retained as necessary for billing, accounting, fraud prevention, and legal requirements.",
                "Security and diagnostic information may be retained for a reasonable period for security, troubleshooting, and reliability purposes.",
              ]}
            />
            <P>
              When information is no longer reasonably required, we will delete it or
              otherwise dispose of it in accordance with our practices and applicable law.
            </P>
          </Section>

          <Section n="16" title="Account Deletion">
            <P>
              You may request deletion of your Aks account and associated personal
              information by contacting:
            </P>
            <P>
              <Mail />
            </P>
            <P>We may need to verify your identity before processing a deletion request.</P>
            <P>
              After a valid request, we will take reasonable steps to delete personal
              information associated with your account, subject to information that we
              are required or permitted to retain by law, for security, fraud prevention,
              dispute resolution, accounting, or other legitimate purposes.
            </P>
            <P>
              Information already processed by independent third-party services may be
              subject to those providers&apos; own retention and deletion policies. Where
              applicable, you may also need to request deletion directly from those
              services.
            </P>
            <P>
              See also:{" "}
              <a
                href="/delete-account"
                className="font-medium text-[#171717] underline underline-offset-4"
              >
                Delete your account
              </a>
              .
            </P>
          </Section>

          <Section n="17" title="Disconnecting Connected Services">
            <P>
              You can disconnect supported integrations through Aks where that option is
              available.
            </P>
            <P>
              Disconnecting an integration stops Aks from obtaining new information
              through that connection.
            </P>
            <P>
              Information that was already processed or stored before disconnection may
              remain subject to the applicable retention period described in this policy.
            </P>
            <P>
              If you want information held directly by a third-party service deleted, you
              may also need to contact that service.
            </P>
          </Section>

          <Section n="18" title="Your Privacy Rights">
            <P>
              Depending on where you live and the laws that apply to you, you may have
              rights regarding your personal information.
            </P>
            <P>These may include the right to:</P>
            <List
              items={[
                "Request access to personal information we hold about you",
                "Request correction of inaccurate information",
                "Request deletion of your information",
                "Request a copy of certain information",
                "Withdraw consent where processing is based on consent",
                "Object to certain processing",
                "Request restriction of certain processing",
                "Disconnect integrations",
                "Control device permissions through your operating system",
              ]}
            />
            <P>To exercise a privacy right, contact:</P>
            <P>
              <Mail />
            </P>
            <P>
              We may ask for information necessary to verify your identity and protect
              your account.
            </P>
            <P>
              You may also have the right to complain to a data-protection or privacy
              authority in your country or region.
            </P>
          </Section>

          <Section n="19" title="International Data Transfers">
            <P>
              Aks and the third-party services it uses may process information in
              countries other than the country where you live.
            </P>
            <P>
              Where required by applicable law, we take reasonable steps to provide
              appropriate safeguards for international transfers of personal information.
            </P>
          </Section>

          <Section n="20" title="Children">
            <P>
              Aks is not intended for children below the minimum age permitted by
              applicable law.
            </P>
            <P>
              We do not knowingly collect personal information from children in violation
              of applicable legal requirements.
            </P>
            <P>
              If you believe that a child has provided personal information to Aks,
              contact <Mail /> so we can review the situation and take appropriate
              action.
            </P>
          </Section>

          <Section n="21" title="Third-Party Websites and Services">
            <P>
              Aks may contain links to or integrations with third-party websites and
              services.
            </P>
            <P>We are not responsible for the privacy practices of independent third parties.</P>
            <P>
              When you use a third-party service, that service&apos;s own privacy policy
              and terms may apply.
            </P>
          </Section>

          <Section n="22" title="Changes to This Privacy Policy">
            <P>
              We may update this Privacy Policy when Aks changes, when new features are
              introduced, or when legal or regulatory requirements change.
            </P>
            <P>
              When we make changes, we will update the Last Updated date at the top of
              this policy.
            </P>
            <P>
              If a change is significant, we may provide additional notice where
              appropriate.
            </P>
          </Section>

          <Section n="23" title="Contact Us">
            <P>
              If you have questions, concerns, or requests about this Privacy Policy or
              your personal information, contact:
            </P>
            <P>
              Harsh Kumar Singh
              <br />
              Miyal
              <br />
              Aks
            </P>
            <P>
              Privacy email: <Mail />
            </P>
          </Section>

          <Reveal>
            <section className="mt-4 rounded-[10px] border border-[#E8E8E5] bg-white p-5">
              <h2 className="text-[16px] font-medium text-[#171717]">Aks in Short</h2>
              <div className="mt-2 text-[14.5px] leading-[1.7] text-[#6B6B6B]">
                <p>Aks is built around giving you control over what you share.</p>
                <p className="mt-2">
                  You choose what you tell Aks, which services you connect, and which
                  device permissions you allow.
                </p>
                <p className="mt-2">
                  If you no longer want to use Aks, you can request account and
                  personal-data deletion through the contact method provided above.
                </p>
              </div>
            </section>
          </Reveal>
        </div>
      </main>
      <footer className="border-t border-[#E8E8E5]">
        <div className={`${container} flex flex-col gap-2 py-8 sm:flex-row sm:items-center sm:justify-between`}>
          <Logo sub={false} />
          <p className="text-[13px] text-[#9a9a96]">© 2026 {STUDIO_NAME}</p>
        </div>
      </footer>
    </div>
  );
}
